### ISSUE TITLE
Rendering of og: meta data on page.ss

### ISSUE THREAD

**Issue by groundnation** [jonom/silverstripe-share-care#12]
Hi

This is a great looking module, apologies if this is a dumb question, but how do you render the og: meta data on page.ss? I can see the share links work fine for Twitter, Pinterest and the email - but on debugging the Facebook link, it flags that the OG: meta tags are not there.

James

**Comment by jonom** [comment]
Hi @groundnation sorry for the slow reply - the meta tag rendering is handled by the [SS OG](https://github.com/tractorcow/silverstripe-opengraph) module, so you might want to take a look at the documentation there to see what might be causing an issue on your site.
