### ISSUE TITLE
ss4 compatability

### ISSUE THREAD

**Issue by guyvanbael** [jonom/silverstripe-share-care#13]
@jonom Hi Jonathan. Any plans on updating this for Silverstripe 4? I'm using this great module on almost all of our silverstripe projects.. would be great if i could keep on doing this.

Grtz,
guy

**Comment by jonom** [comment]
Hi @guyvanbael, no specific plans but I'm sure I'll get around to it one day (when I need it on a project). If you want to speed things up I'll happily review a pull request 😃

**Comment by Pinchcliffe** [comment]
@jonom Are you working on getting it updated to SS4? Looks like the OpenGraph module is not SS4 compatible yet.

**Comment by guyvanbael** [comment]
@Pinchcliffe for SS4 projects, i'm using this one for the time being...
http://addons.silverstripe.org/add-ons/toastnz/open-graph-meta

**Comment by jonom** [comment]
@Pinchcliffe I have no immediate plans to update this module but I always try to review pull requests promptly, if you or someone else wants to work on upgrading it. I'm always happy to chat about sponsorship too if you want to shift this from my 'free time' workload to my 9-5.

**Comment by jonom** [comment]
BTW here is a promising looking SS4 module that has a lot of overlap with ShareCare: https://github.com/vulcandigital/silverstripe-seo

**Comment by jonom** [comment]
https://github.com/jonom/silverstripe-share-care/releases/tag/v3.0.0
