### ISSUE TITLE
Override Not Working

### ISSUE THREAD

**Issue by gordonbanderson** [jonom/silverstripe-share-care#3]
Firstly I want to say what a great idea for a module, wish I'd thought of it :)

I'm unable to get image override to work.  When I add an override as in the attached is the preview meant to change to the overriding image or not?  I am not seeing this happening, and also in the HTML output the og:image value is of the original image from the models getOGIMage() method, not the override.

``` php
public function getOGImage() {
        return $this->BioImage();
    }
```

![sharecare](https://cloud.githubusercontent.com/assets/7060/13527696/9215b82e-e243-11e5-8c2d-4a640a347d7c.png)

I suspect some extension shenanigans :)

**Comment by jonom** [comment]
Hi Gordon, glad you like it :)

I've just tested this and it works fine for me, so I would suspect that it's a yml problem and the extension is getting added too late. In order for ShareCare's methods to take precedence over those from the Open Graph module they need to be added first.

Can you try separating your share care yml in to a separate sharecare.yml file with following contents and see if that helps:

``` yml
---
Name: sharecare
Before: 'opengraph/*'
---
Page:
  extensions:
    - ShareCareFields
```

If that fixes the problem let me know and I'll update the docs to be clearer.

**Comment by jonom** [comment]
Dr Samuel... :flushed: :scream:

**Comment by gordonbanderson** [comment]
Will have a look over the weekend, but noted re priority of config

**Comment by gordonbanderson** [comment]
Caveat - I have cycled 110km today in tropical heat so not 100% on the ball :)

The above config appears to mirror that of /share-care/config/ShareCare.yml, and if I edit to this I see no share care, as expected.

```
---
Name: sharecare
Before: 'opengraph/*'
---
Page:
  extensions:
#    - ShareCare
#    - ShareCareFields
#ShareCare:
#  pinterest: true
#  twitter_username: 'test-user'
```

With the default config I am seeing ShareCare appearing, but the ShareCareFields already seem enabled

```
---
Name: sharecare
Before: 'opengraph/*'
---
Page:
  extensions:
    - ShareCare
#    - ShareCareFields
#ShareCare:
#  pinterest: true
#  twitter_username: 'test-user'
```

Grepping through my codebase this is the only place where ShareCare is enabled extension wise.

I will need to strip this down to a minimal example I think to get to the bottom of the issue.

**Comment by gordonbanderson** [comment]
I still can't get this to work....

Steps to re-create:
- Install clean SilverStripe: `composer create-project silverstripe/installer www`
- Install share-care: `require jonom/silverstripe-share-care "dev-master"`
- Install test module: `git clone git@github.com:gordonbanderson/sharecaretest.git`

After setting up SilverStripe through a browser, go to the editing section and add a page of type `PageAndImage`.  When I add an image and try to override this with override fields it does not work as I would expect it to.

**Comment by jonom** [comment]
I followed your steps but that [sharecaretest](https://github.com/gordonbanderson/sharecaretest) module is empty :stuck_out_tongue: 

So far works as expected though, only the preview is added out of the box, no fields. If you fix up that test module I'll check it out.

**Comment by gordonbanderson** [comment]
Apologies, not enough Sunday morning coffee.  Pushed now https://github.com/gordonbanderson/sharecaretest

**Comment by jonom** [comment]
Hi @gordonbanderson I've tested again and looked at your code - everything is working exactly as expected for me so we have a misunderstanding or miscommunication about how to action your goal.

`PageAndImage::getOGImage()` is the authoritative method in your example and the only version of the method that will get called. As such MainImage() is the only thing that will ever be used for the OG image.

My guess is that you just want to change how the default image is chosen, but allow this to be overridden on the Share tab. In that case you need to remove the `getOGImage()` method from `PageAndImage` and instead include something like this:

``` php
/**
 * Provide a better default OG image for pages
 */
public function getDefaultOGImage() {
    // Use hero image if available
    if ($this->MainImageID) {
        return $this->MainImage();
    }
    // Fallback to website's apple-touch-icon
    if (file_exists(BASE_PATH . '/apple-touch-icon.png')) {
        return Director::absoluteURL('apple-touch-icon.png', true);
    }
}
```

Let me know if that fixes it up for you. Have added an example to the ReadMe to hopefully make this a bit clearer!

**Comment by gordonbanderson** [comment]
hi @jonom 

Thanks for taking time out to have a look.  My thinking was along these lines:

1) Use override image first if it's available
2) Use the 'main image' if that's available
3) Use some final catch all if neither of the above available

Your previous code example only seems to deal with cases 2) and 3)

I can add a check for the Share Care override image in there I guess, checking for the extension existence first, to achieve the goal I want

Cheers

Gordon

**Comment by jonom** [comment]
> 1) Use override image first if it's available
> 2) Use the 'main image' if that's available
> 3) Use some final catch all if neither of the above available

@gordonbanderson if you test my suggestion you should find that it does exactly this. The override image will be the first choice, as set in `getOGImage()` in the `ShareCareFields` extension. If no override image is available it will fallback to your custom `getDefaultOGImage()` method. Make sense?

**Comment by gordonbanderson** [comment]
About to cycle 25km into Bangkok.  I'll have a look again this evening my time :)

**Comment by gordonbanderson** [comment]
Took me a bit longer to get back to you, but I now have it working on the project I was concerned about.  Removing the getOGImage() resolved the issue.
