### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by derralf** [jonom/silverstripe-share-care#31]
An Access Token is now required:
https://developers.facebook.com/docs/graph-api/reference/v8.0/url#readfields-3

It would be great if one could put an access_token in the config of the module.

Edit:
e.g.:

ShareCare.php line 186
```
$client->request('GET', 'https://graph.facebook.com/', [
    'query' => [
        'id' => $this->owner->AbsoluteLink(),
        'scrape' => true,
        'access_token' => $this->config()->get('facebook_access_token')
    ]
]);
```

app/_config/mysharecare.yml
```
JonoM\ShareCare\ShareCare:
  facebook_access_token: 'xxxxxxxxxxxxxxx|yyyyyyyyyyyyyyyyyyyyyyyyy'
```

**Comment by jonom** [comment]
@derralf I think the docs always said this was required, but I never found it to be true. Bummer if it is now 😞

Would you be willing to open a pull request for this change? A few things I would like to see:

- [ ] Support env var (recommended) or yml config
    * E.g. `'access_token' => Environment::getEnv('SS_SHARECARE_FBACCESSTOKEN') || $this->config()->get('facebook_access_token')`
- [ ] Document how to obtain an access token and which type
    * Probably an [app token](https://developers.facebook.com/docs/facebook-login/access-tokens/#apptokens) or [client token](https://developers.facebook.com/docs/facebook-login/access-tokens/#clienttokens)?
- [ ] Document how to set token

**Comment by derralf** [comment]
Hi @jonom,
I am neither a Facebook expert nor a native English speaker. Would the following instructions be OK?


### How to obtain a Facebook App Token and use it with the Share Care module

#### 1. Create a Facebook App

* Go to https://developers.facebook.com/apps and create an app.  
* Name it "ShareCareScrapingAccess" for example.
* If you don't already have a Facebook Developer Account, you may be asked to create one first.

#### 2. Get the App-Token

* Go to <https://developers.facebook.com/tools/explorer>
* In Dropdown "User or Page" select  "App Token"  
(because User Tokens will expire after some time, that's why you'd like to use the App Token.  )
* In Dropdown "Facebook App" select your newly created App (e.g. "ShareCareScrapingAccess")
* For a test set the mode in the top form to `get` and the value to `?scrape=1&id=https://www.mydomain.com`
* Copy Token from the input Field at the to top.



The token will look something like this:  
11111111111111111|ABcDEfG1hi1j1K11LMNop1QRSTU

You can also view your created App tokens afterwards here:  
https://developers.facebook.com/tools/accesstoken/


#### 3. Use the obtained token with Share Care module

You can set the token either in your .env file:

```
SS_SHARECARE_FBACCESSTOKEN="11111111111111111|ABcDEfG1hi1j1K11LMNop1QRSTU"
```

or in a yml configuration file:

```
JonoM\ShareCare\ShareCare:
  facebook_access_token: '11111111111111111|ABcDEfG1hi1j1K11LMNop1QRSTU'
```

**Comment by jonom** [comment]
@derralf looks great!

**Comment by derralf** [comment]
just created a pull request #32
