### ISSUE TITLE
Incorrect URL encoding

### ISSUE THREAD

**Issue by lozcalver** [jonom/silverstripe-share-care#4]
Email share links use `urlencode()`, which results in an email subject of: `Thought+you+might+like+this`. Switching to `rawurlencode()` seems to fix the issue.

I’m not sure if the same applies to other places that `urlencode()` is used, but from memory `rawurlencode()` is the safer option for query string parameters

**Comment by jonom** [comment]
Cheers Loz you're right... guess I never tested that email share link! Most of the links seem happy with either urlencode or rawurlencode but rawurlencode seems like the best practice.

**Comment by lozcalver** [comment]
Awesome, thanks! :+1:
