### ISSUE TITLE
sharecarepreview on dataobjects (modeladmin) not working

### ISSUE THREAD

**Issue by guyvanbael** [jonom/silverstripe-share-care#6]
Hi,

I installed the module succesfully (ss3.3.1) using composer and share tab is added to every page.
But i also have a dataobject using modeladmin with a show-action so it can be rendered as a page (Referentie (has titel, tekst and a has_many referentiefotos (images)and hasmany studielinks).In the config i added sharecarepreview, but in the cms nothing is changed in the referentie databobject. I added some screenshots. Can somebody shine a light on this?
Bu the way... i 'm getting an error that ShareCarePreview does not exist...

<img width="2032" alt="config" src="https://cloud.githubusercontent.com/assets/3098809/14203294/7ba85310-f7fd-11e5-8969-9a12f58942df.png">
<img width="2032" alt="dataobject in modeladmin" src="https://cloud.githubusercontent.com/assets/3098809/14203295/7baa7abe-f7fd-11e5-8887-f92ef62e57f3.png">

**Comment by jonom** [comment]
Hi @guyvanbael sorry for the late reply, only seeing this now. You probably also need to add

``` yml
Referentie:
  extensions:
    - 'OpenGraphObjectExtension'
```

to your dataobject. It is added to Page automatically by the Open Graph module.

**Comment by guyvanbael** [comment]
Hi Jonathan,
No problem for the delay. Thanx for helping out.
